SHELL = /bin/sh
FC = _FC_
CC = _CC_
FOPT     = _FOPT_
FGEN     =  
LDFLAGS = _LDFLAGS_
LIBS   = _R_LIBS_
DESTDIR  = .
EXECNAME = lapwso

###############################################################################
###############################################################################


FFLAGS = $(FGEN) $(FOPT)
EXEC = $(DESTDIR)/$(EXECNAME)

#..............................................................................
#
#  Routines which can be compiled unmodified
#
OBJS = reallocate.o modules.o abclm.o    couple.o   errclr.o  errflg.o   garadme.o gtfnam.o  \
        harmon2.o  atpar.o    hmsec.o   init.o     kptin.o   latgen2.o \
        outwin.o   rint13.o  lapwso.o   cali.o    sphbes.o vnsrint.o  \
        lomain.o   abc.o      cputim.o  dvbes1.o   bess.o    lagder.o  \
        rotate.o   ylm.o      harmon.o  sphbru.o   outerr.o  lap_bp.o \
        inouh.o    diracout.o inth.o    select.o   abc_r.o   rlomain.o \
        kptout.o  angle.o gaunt1.o gaunt2.o \
        dergl.o    hscalc.o   dergl2.o  vderiv.o  rotdef.o \
        symop.o garadorb.o hns.o hsocalc.o horbcalc.o vorblo.o euler.o

OBJSMOD = abc.o abc_r.o abclm.o angle.o atpar.o cali.o couple.o \
          dergl.o dergl2.o diracout.o garadme.o garadorb.o harmon.o \
          hns.o horbcalc.o hscalc.o hsocalc.o \
          init.o inouh.o kptin.o kptout.o lapwso.o latgen2.o lomain.o opnfs.o \
          outwin.o rint13.o rlomain.o rotdef.o stern.o vderiv.o vectest.o \
          vnsrint.o vorblo.o


#..............................................................................

$(EXEC): $(OBJS)
	$(FC) -o $(EXEC) $(OBJS) $(LDFLAGS) $(LIBS)
#..............................................................................
#
#  All routines depend upon an include file (contains common PARAMETERS)
#
$(OBJS):		Makefile
$(OBJSMOD):		modules.o

clean:
	-rm -f *.o _tmp_.* *.P .real .complex *.mod

#..............................................................................
#
#
.f.o:
	$(FC) $(FFLAGS) -c $<
#${OBJS} : %.o : %.f90
#	$(FC) $(FFLAGS) -c $< 

