      FUNCTION SPHBRU(N,X)
      IMPLICIT REAL*8(A-H,O-Z)
      DATA TOL/1.D-14/
      I=0
      BB=1.D0
   10 CONTINUE
      I=I+1
      FAC=1.D0
      DO 100 J=1,I
      FAC=FAC/DFLOAT(J)
  100 CONTINUE
      FACD=1.D0
      DO 110 J=1,I
      FACD=FACD/(2.D0*DFLOAT(N)+3.D0+2.D0*DFLOAT(J-1))
  110 CONTINUE
      DBB=(X*X/2.D0)**I*FAC*FACD
      BB=BB+DBB*(-1.D0)**I
      IF(DBB.LT.TOL) GO TO 99
      GO TO 10
   99 SPHBRU=BB
      RETURN
      END
